com.github.ben-manes.caffeine:* = 3.2.4
com.google.auto.service:auto-service = 1.1.1
com.google.errorprone:error_prone_* = 2.46.0
com.google.guava:guava = 33.6.0-jre
com.palantir.safe-logging:* = 3.17.0
com.palantir.tracing:* = 6.36.0
com.palantir.tritium:* = 0.134.0
org.assertj:* = 3.27.7
org.immutables:value = 2.12.2
org.junit.jupiter:* = 6.1.1
org.junit.platform:* = 6.1.1
